server:
  port: 1000

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:aaa/config.git
          search-paths: config
      label: master
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: cloud-config
    prefer-ip-address: true