server:
  port: 9004

spring:
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 666666

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: # entity 别名类所在包

# 设置 feign 客户端超时时间
# ReadTimeout 和 ConnectTimeout 的顺序不能更换，否则不生效
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: order9004
    prefer-ip-address: true
logging:
  level:
    # Feign 日志以什么级别控制哪个接口
    me.alphar.springcloud.order.service.PaymentFeignService: debug
